[versions]
agp = '8.1.2'
androidx-junit = "1.1.5"
appcompat = "1.6.1"
auto-service = "1.1.1"
constraintlayout = "2.1.4"
core-ktx = "1.12.0"
espresso-core = "3.5.1"
kotlinpoet = "1.15.3"
lint = '31.2.0' # = agp + 23.0.0
kotlin = '1.9.22'
junit = '4.13.2'
mapstruct-processor = "1.5.2.Final"
mapstruct = "1.5.5.Final"
material = "1.11.0"


[libraries]
# For a description of the below dependencies, see the main project README
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
auto-service = { module = "com.google.auto.service:auto-service", version.ref = "auto-service" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "lint" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "lint" }
lint-cli = { group = "com.android.tools.lint", name = "lint", version.ref = "lint" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "lint" }
junit = { group = "junit", name = "junit", version.ref  = "junit" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstruct-processor" }
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstruct" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[bundles]
lint-api = [
    "kotlin-stdlib",
    "lint-api",
    # You typically don't need this one, but it does have some utilities
    # like the API database that some lint checks may want to use
    #"lint-checks",
]
lint-tests = [
    "junit",
    "lint-cli",
    "lint-tests"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-lint = { id = "com.android.lint", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }